#! bin/sh

echo ""
echo ""
echo ""
echo ""
echo ""
echo ""




while true; do
    read -p "have you got valheim installed already?" yn
    case $yn in
        [Yy]* ) echo "proceding with installation"
        [Nn]* ) echo "please install valheim dedicated server on steam otherwise this script may not work"
        * ) echo "Please answer y or n:";;
    esac
done









while true; do
    read -p "have you got valheim installed already?" yn
    case $yn in
        [Yy]* ) echo "all commands being used are from https://developer.valvesoftware.com/wiki/SteamCMD"
          useradd -m steam
          cd /home/steam
          sudo apt install steamcmd
        [Nn]* ) echo "would you like to make a root account for SteamCMD (this is more secure)"
            sudo apt install steamcmd
        * ) echo "Please answer y or n:";;
    esac
done










while true; do
    read -p "are you running a 64-bit system 64-bit systems require multiverse" yn
    case $yn in
        [Yy]* ) echo "proceding with installation"
           sudo add-apt-repository multiverse
           sudo dpkg --add-architecture i386
           sudo apt update
           echo "installing dependencies.........."
            sudo apt install lib32gcc1 steamcmd
            echo "successful"
        [Nn]* ) echo "please install valheim dedicated server on steam otherwise this script may not work"
           echo "installing dependencies.........."
           sudo apt-get install lib32gcc1
           echo "successful"
        * ) echo "Please answer y or n:";;
    esac
done










echo "placing all scripts in the relevant folders"
#enter password and append to script
  cd root/of/valheim/dedicated/server/directory/valheim.sh
#find a way to put this script into the valheim server directory
  #!/bin/sh export templdpath=$LD_LIBRARY_PATH
  export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
  export SteamAppID=892970

  echo "Starting server PRESS CTRL-C to exit"
  ./valheim_server.x86_64 -name "" -port 2456 -nographics -batchmode -world "" -password "you dont need these <> for the password" -public 1
  export LD_LIBRARY_PATH=$templdpath

cd root/of/valheim/dedicated/server/directory/InstallUpdate.sh
  #find a way to put this script into the InstallUpdate.sh file
  steamcmd +@sSteamCmdForcePlatformType linux +force_install_dir /path/to/server +login anonymous +app_update 896660 validate +quit #!/bin/sh

echo "Tip: Make a local copy of this script to avoid it being overwritten by steam."
echo "NOTE: Minimum password length is 5 characters & Password cant be in the server name."
echo "NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall."
echo "Tip: run the InstallUpdate.sh file everytime the game updates make sure to exit your server before running this"
echo "make sure password is changed"
