#! bin/sh
echo "have you got valheim installed already"

choice y/n
if y:
  echo "proceeding with installation"

if n:
  echo "please install valheim dedicated server first make otherwise this script may not work"
  exit/cancel script dont exit terminal straight away
echo "would you like to proceed with installation? note that this script is specifically for debian systems"
choice y/n
echo "all commands being used are from https://developer.valvesoftware.com/wiki/SteamCMD"
echo "would you like to make a root account for SteamCMD (this is more secure)"
choice y/n

if y:
  useradd -m steam
  cd /home/steam
  sudo apt install steamcmd

if n:
  sudo apt install steamcmd

echo "are you running a 64-bit system 64-bit systems require multiverse"
choice y/n

if y:
  sudo add-apt-repository multiverse
  sudo dpkg --add-architecture i386
  sudo apt update
  echo "installing dependencies.........."
  sudo apt install lib32gcc1 steamcmd
if n:
  echo "installing dependencies.........."
  sudo apt-get install lib32gcc1

echo "successful"

echo "what would you like your password to be to the valheim_server:" # make this the dots to hide it 
echo "placing all scripts in the relevant folders"
#enter password and append to script
  cd root/of/valheim/dedicated/server/directory/valheim.sh
#find a way to put this script into the valheim server directory
  #!/bin/sh export templdpath=$LD_LIBRARY_PATH
  export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
  export SteamAppID=892970

  echo "Starting server PRESS CTRL-C to exit"
  ./valheim_server.x86_64 -name "" -port 2456 -nographics -batchmode -world "" -password "you dont need these <> for the password" -public 1
  export LD_LIBRARY_PATH=$templdpath

cd root/of/valheim/dedicated/server/directory/InstallUpdate.sh
  #find a way to put this script into the InstallUpdate.sh file
  steamcmd +@sSteamCmdForcePlatformType linux +force_install_dir /path/to/server +login anonymous +app_update 896660 validate +quit #!/bin/sh

echo "Tip: Make a local copy of this script to avoid it being overwritten by steam."
echo "NOTE: Minimum password length is 5 characters & Password cant be in the server name."
echo "NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall."
echo "Tip: run the InstallUpdate.sh file everytime the game updates make sure to exit your server before running this"
echo "make sure password is changed"
